version: '3'

services:
  webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
