version: '3'

services:
  webclient:
    image: webclient
    build:
      context: ./WebClient
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbit.mq

  sql.data:
    image: "microsoft/mssql-server-linux"
    volumes:
      - sqldata:/sql/data
    environment:
      - SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  rabbit.mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

     

volumes:
  sqldata:
