version: '3'

services:
  webclient:
    image: webclient
    build:
      context: ./WebClient
      dockerfile: Dockerfile
    depends_on:
      - webapi
      - rabbit.mq

  webapi:
    image: webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbit.mq

  sql.data:
    image: "microsoft/mssql-server-linux"
    volumes:
      - sqldata:/sql/data
    environment:
      - SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  rabbit.mq:
    image: rabbitmq:3-management
    volumes:
      - rabbitdata:/rabbit/data
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=Passw0rd
    ports:
      - "5673:5672"
      - "15673:15672"



volumes:
  sqldata:
  rabbitdata: