// <auto-generated />
using Borg.Platform.EStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Borg.Platform.EStore.Data.Migrations
{
    [DbContext(typeof(EStoreDbContext))]
    [Migration("20180502200503_estore2")]
    partial class estore2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Borg.Platform.EStore.Data.Entities.ComponentState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ComponentState","estore");
                });

            modelBuilder.Entity("Borg.Platform.EStore.Data.Entities.PriceListState", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("Code");

                    b.Property<string>("Title");

                    b.HasKey("Id", "LanguageCode")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PriceListState","estore");
                });

            modelBuilder.Entity("Borg.Platform.EStore.Data.Entities.PriceListState", b =>
                {
                    b.HasOne("Borg.Platform.EStore.Data.Entities.ComponentState", "ComponentState")
                        .WithOne("PriceList")
                        .HasForeignKey("Borg.Platform.EStore.Data.Entities.PriceListState", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
