// <auto-generated />
using Borg.Cms.Basic.Lib.Features.Navigation;
using Borg.Cms.Basic.Lib.System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Borg.Cms.Basic.Lib.System.Data.Migrations
{
    [DbContext(typeof(BorgDbContext))]
    [Migration("20171229195909_NavigationItemRecord")]
    partial class NavigationItemRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Borg.Cms.Basic.Lib.Features.Navigation.NavigationItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("IsPublished");

                    b.Property<int>("ItemType");

                    b.Property<int>("ParentId");

                    b.Property<double>("Weight");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("NavigationItemRecords","borg");
                });
#pragma warning restore 612, 618
        }
    }
}
